In [1]:
import os

print(os.listdir("../data"))

['student_dataset.csv']

In [41]:
import pandas as pd
df = pd.read_csv("../data/student_dataset.csv")
df.head()

,StudentID,StudyHours,Attendance,PreviousScore,AssignmentScore,SleepHours,PreviousFailures,Result
0,S001,2.0,62,45,48,5.0,2,Fail
1,S002,3.0,68,52,55,6.0,1,Fail
2,S003,4.0,75,58,62,6.5,1,Pass
3,S004,5.0,82,65,70,7.0,0,Pass
4,S005,1.5,55,40,42,5.0,3,Fail

In [4]:
%pip install pandas numpy scikit-learn joblib matplotlib seaborn

Requirement already satisfied: pandas in C:\Users\saite\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (3.0.2)
Requirement already satisfied: numpy in C:\Users\saite\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (2.4.4)
Requirement already satisfied: scikit-learn in C:\Users\saite\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (1.8.0)
Requirement already satisfied: joblib in C:\Users\saite\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (1.4.2)
Requirement already satisfied: matplotlib in C:\Users\saite\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (3.11.0)
Requirement already satisfied: seaborn in C:\Users\saite\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\saite\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\saite\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from pandas) (2026.1)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\saite\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: threadpoolctl>=3.2.0 in C:\Users\saite\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\saite\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\saite\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\saite\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\saite\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\saite\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from matplotlib) (26.1)
Requirement already satisfied: pillow>=9 in C:\Users\saite\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\saite\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in C:\Users\saite\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np
import sklearn
import joblib

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

print("All packages imported successfully!")
print("Joblib version:", joblib.__version__)
print("Scikit-learn version:", sklearn.__version__)

All packages imported successfully!
Joblib version: 1.4.2
Scikit-learn version: 1.8.0

In [3]:
#Load the Dataset
data_path = "../data/student_dataset.csv"
df = pd.read_csv(data_path)
print("Dataset loaded successfully!")

Dataset loaded successfully!

In [4]:
df.head()

,StudentID,StudyHours,Attendance,PreviousScore,AssignmentScore,SleepHours,PreviousFailures,Result
0,S001,2.0,62,45,48,5.0,2,Fail
1,S002,3.0,68,52,55,6.0,1,Fail
2,S003,4.0,75,58,62,6.5,1,Pass
3,S004,5.0,82,65,70,7.0,0,Pass
4,S005,1.5,55,40,42,5.0,3,Fail

In [5]:
df.shape

(50, 8)

In [6]:
df.columns

Index(['StudentID', 'StudyHours', 'Attendance', 'PreviousScore',
       'AssignmentScore', 'SleepHours', 'PreviousFailures', 'Result'],
      dtype='str')

In [7]:
df.info

<bound method DataFrame.info of    StudentID  StudyHours  Attendance  PreviousScore  AssignmentScore  \
0       S001         2.0          62             45               48
1       S002         3.0          68             52               55
2       S003         4.0          75             58               62
3       S004         5.0          82             65               70
4       S005         1.5          55             40               42
5       S006         6.0          88             72               78
6       S007         2.5          64             48               50
7       S008         7.0          92             80               85
8       S009         3.5          70             55               60
9       S010         2.0          58             43               45
10      S011         5.5          85             68               75
11      S012         4.5          78             61               65
12      S013         1.0          52             35               40
13      S014         6.5          90             76               82
14      S015         3.0          66             50               54
15      S016         5.0          80             63               68
16      S017         2.5          60             44               47
17      S018         7.5          94             85               90
18      S019         4.0          72             57               61
19      S020         1.5          57             39               43
20      S021         6.0          86             70               76
21      S022         3.5          69             53               57
22      S023         2.0          61             46               44
23      S024         5.5          83             67               72
24      S025         4.5          76             60               64
25      S026         1.0          50             32               38
26      S027         6.5          89             74               80
27      S028         2.5          63             47               49
28      S029         5.0          81             66               71
29      S030         3.0          67             51               56
30      S031         7.0          93             82               88
31      S032         4.0          74             59               63
32      S033         1.5          54             38               41
33      S034         5.5          84             69               74
34      S035         2.0          59             42               46
35      S036         6.0          87             73               79
36      S037         3.5          71             56               59
37      S038         2.5          65             49               52
38      S039         7.5          95             88               92
39      S040         4.5          77             62               67
40      S041         1.0          53             36               39
41      S042         5.0          82             64               70
42      S043         3.0          68             50               53
43      S044         6.5          91             78               84
44      S045         4.0          73             58               62
45      S046         2.0          60             41               45
46      S047         5.5          86             71               77
47      S048         3.5          70             54               58
48      S049         1.5          56             37               42
49      S050         6.0          88             75               81

    SleepHours  PreviousFailures Result
0          5.0                 2   Fail
1          6.0                 1   Fail
2          6.5                 1   Pass
3          7.0                 0   Pass
4          5.0                 3   Fail
5          7.5                 0   Pass
6          6.0                 2   Fail
7          8.0                 0   Pass
8          6.5                 1   Pass
9          5.5                 2   Fail
10         7.0                 0   Pass
11         6.5                 0   Pass
12         5.0                 3   Fail
13         7.5                 0   Pass
14         6.0                 2   Fail
15         7.0                 0   Pass
16         5.5                 2   Fail
17         8.0                 0   Pass
18         6.5                 1   Pass
19         5.0                 3   Fail
20         7.5                 0   Pass
21         6.0                 1   Pass
22         5.5                 2   Fail
23         7.0                 0   Pass
24         6.5                 1   Pass
25         4.5                 3   Fail
26         7.5                 0   Pass
27         5.5                 2   Fail
28         7.0                 0   Pass
29         6.0                 1   Fail
30         8.0                 0   Pass
31         6.5                 1   Pass
32         5.0                 3   Fail
33         7.0                 0   Pass
34         5.5                 2   Fail
35         7.5                 0   Pass
36         6.5                 1   Pass
37         6.0                 2   Fail
38         8.0                 0   Pass
39         6.5                 1   Pass
40         5.0                 3   Fail
41         7.0                 0   Pass
42         6.0                 2   Fail
43         7.5                 0   Pass
44         6.5                 1   Pass
45         5.5                 2   Fail
46         7.0                 0   Pass
47         6.0                 1   Pass
48         5.0                 3   Fail
49         7.5                 0   Pass  >

In [39]:
#check for missing values and duplicate records
df.duplicated().sum()

np.int64(0)

In [38]:
#Understand the Target Variable
df["Result"].unique()

<ArrowStringArray>
['Fail', 'Pass']
Length: 2, dtype: str

In [20]:
#Preapare feature columns that are required for prediction, ignore unwanted columns(student_id)from the list
features = [
    "StudyHours",
    "Attendance",
    "PreviousScore",
    "AssignmentScore",
    "SleepHours",
    "PreviousFailures",
]
target = "Result"
X = df[features]  #  return  only given columns values 
Y = df[target]     # return only churn column values 
print( X.head() )
print( Y.head() )

   StudyHours  Attendance  PreviousScore  AssignmentScore  SleepHours  \
0         2.0          62             45               48         5.0
1         3.0          68             52               55         6.0
2         4.0          75             58               62         6.5
3         5.0          82             65               70         7.0
4         1.5          55             40               42         5.0

   PreviousFailures
0                 2
1                 1
2                 1
3                 0
4                 3
0    Fail
1    Fail
2    Pass
3    Pass
4    Fail
Name: Result, dtype: str

In [21]:
#convert pass/fail into numerical values
Y = Y.map({
    "Fail": 0,
    "Pass": 1
})
display(Y.head())

0    0
1    0
2    1
3    1
4    0
Name: Result, dtype: int64

In [22]:
#split the dataset into training and testing data
X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size=0.20,
    random_state=42,
    stratify=Y
)
print("Total records :", len(X))
print("Training data :", len(X_train))
print("Testing data  :", len(X_test))

Total records : 50
Training data : 40
Testing data  : 10

In [23]:
#perform feature scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [24]:
# Create the ML Model
model = LogisticRegression(
    random_state=42
)

In [26]:
# train the model
model.fit(
    X_train_scaled,
    Y_train
)
print("Model training completed!")

Model training completed!

In [40]:
# Make Predictions on test data
Y_pred = model.predict(
    X_test_scaled
)
print("Predictions:")
print(Y_pred)

Predictions:
[0 1 0 0 1 1 1 1 0 1]

In [29]:
# compare actual vs predicted
comparison = pd.DataFrame({
    "Actual": Y_test.values,
    "Predicted": Y_pred
})
comparison

   Actual  Predicted
0       0          0
1       1          1
2       0          0
3       0          0
4       1          1
5       1          1
6       1          1
7       1          1
8       0          0
9       1          1

In [30]:
import joblib
#Save the Trained Model
model_path = "../models/Result_model.pkl"
joblib.dump(
    model,
    model_path
)
print("Model saved successfully!")

Model saved successfully!

In [31]:
# save the scalar
scaler_path = "../models/scaler.pkl"
joblib.dump(
    scaler,
    scaler_path
)
print("Scaler saved successfully!")

Scaler saved successfully!

In [33]:
# load  the model 
loaded_model = joblib.load(
    "../models/Result_model.pkl"
)
loaded_scaler = joblib.load(
    "../models/scaler.pkl"
)
print("Model and scaler loaded successfully!")

Model and scaler loaded successfully!

In [34]:
#New Customer Prediction
# load the new customer
new_customer = pd.DataFrame([
    {
         "StudyHours": 6,
         "Attendance": 85,
         "PreviousScore": 72,
         "AssignmentScore": 80,
         "SleepHours": 7,
         "PreviousFailures": 0
    }
])
new_customer

,StudyHours,Attendance,PreviousScore,AssignmentScore,SleepHours,PreviousFailures
0,6,85,72,80,7,0

In [36]:
# The model was trained using scaled data. 
# So we must scale the new customer's data using the same saved scaler.
new_customer_scaled = loaded_scaler.transform(
    new_customer
)
#prediction
prediction = loaded_model.predict(
    new_customer_scaled
)
print("Predictions:", prediction)

Predictions: [1]

In [37]:
#prediction 
if prediction[0] == 1:
    print("Result: Pass")
else:
    print("Result: Fail")

Result: Pass